#!/bin/bash
code --install-extension ms-vscode.cpptools
code --install-extension ms-python.python
code --install-extension ms-dotnettools.csharp
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vscode.Go
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode.cmake-tools
code --install-extension eamodio.gitlens
code --install-extension vscode-icons-team.vscode-icons
code --install-extension formulahendry.code-runner
code --install-extension redhat.vscode-yaml
code --install-extension christian-kohler.path-intellisense
code --install-extension christian-kohler.npm-intellisense
code --install-extension Equinusocio.vsc-material-theme
code --install-extension Shan.code-settings-sync
code --install-extension magicstack.MagicPython
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-azuretools.vscode-docker
code --install-extension webrender.synthwave-x-fluoromachine

code --install-extension okteto.remote-kubernetes
code --install-extension okteto.kubernetes-context

code-insiders --install-extension ms-vscode.cpptools
code-insiders --install-extension ms-python.python
code-insiders --install-extension ms-dotnettools.csharp
code-insiders --install-extension msjsdiag.debugger-for-chrome
code-insiders --install-extension ms-vscode-remote.remote-wsl
code-insiders --install-extension ms-vscode.PowerShell
code-insiders --install-extension ms-vscode.Go
code-insiders --install-extension ms-vscode-remote.remote-ssh
code-insiders --install-extension ms-vscode.cmake-tools
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension vscode-icons-team.vscode-icons
code-insiders --install-extension formulahendry.code-runner
code-insiders --install-extension redhat.vscode-yaml
code-insiders --install-extension christian-kohler.path-intellisense
code-insiders --install-extension christian-kohler.npm-intellisense
code-insiders --install-extension Equinusocio.vsc-material-theme
code-insiders --install-extension Shan.code-settings-sync
code-insiders --install-extension magicstack.MagicPython
code-insiders --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code-insiders --install-extension ms-azuretools.vscode-docker
code-insiders --install-extension webrender.synthwave-x-fluoromachine